import { UserAccount } from '../types';
import { apiClient } from './client';
import { mockStore } from '../mock/store';

export interface LoginResponse {
  success: boolean;
  token: string;
  user: UserAccount;
}

export const authService = {
  async login(email: string, password: string): Promise<LoginResponse> {
    if (!apiClient.isMock) {
      try {
        const res = await apiClient.request<LoginResponse>('/auth/login', {
          method: 'POST',
          body: JSON.stringify({ email, password }),
        });

        if (res.token && res.user) {
          localStorage.setItem('seekers_auth_token', res.token);
          localStorage.setItem('seekers_auth_user', JSON.stringify(res.user));
          window.dispatchEvent(new Event('seekers_auth_changed'));
          return res;
        }
      } catch (err: any) {
        // If the error was generated by the backend server (e.g. 401 invalid password, 403 suspended, etc.)
        // Rethrow it immediately so the user interface displays the real failure reason!
        const msg = err.message || '';
        const isNetworkFailure =
          msg.toLowerCase().includes('failed to fetch') ||
          msg.toLowerCase().includes('networkerror') ||
          msg.toLowerCase().includes('connection refused');

        if (!isNetworkFailure) {
          throw err;
        }
        console.warn('Backend unreachable, checking local fallback store:', err.message);
      }
    }

    // Fallback ONLY when backend is completely unreachable:
    const users = mockStore.getUsers();
    const matched = users.find((u) => u.email.toLowerCase() === email.toLowerCase());

    if (!matched) {
      throw new Error('Invalid email or password. Operator account not found.');
    }

    if (matched.status === 'Suspended') {
      throw new Error('This operator account is suspended. Contact Director.');
    }

    if (password !== 'seekers2026') {
      throw new Error('Invalid password. Please check your credentials.');
    }

    const token = `sk_sess_local_${matched.id}_${Date.now()}`;
    const user = { ...matched, lastLogin: new Date().toLocaleString() };

    localStorage.setItem('seekers_auth_token', token);
    localStorage.setItem('seekers_auth_user', JSON.stringify(user));
    window.dispatchEvent(new Event('seekers_auth_changed'));

    return {
      success: true,
      token,
      user,
    };
  },

  async getMe(): Promise<UserAccount | null> {
    const token = typeof window !== 'undefined' ? localStorage.getItem('seekers_auth_token') : null;
    if (!token) return null;

    try {
      if (!apiClient.isMock) {
        const res = await apiClient.request<{ user: UserAccount }>('/auth/me');
        if (res.user) {
          localStorage.setItem('seekers_auth_user', JSON.stringify(res.user));
          return res.user;
        }
      }
    } catch {
      // Fall through to cached user
    }

    return this.getCurrentUser();
  },

  getCurrentUser(): UserAccount | null {
    if (typeof window === 'undefined') return null;
    try {
      const stored = localStorage.getItem('seekers_auth_user');
      if (stored) return JSON.parse(stored);
    } catch {}
    return null;
  },

  isAuthenticated(): boolean {
    if (typeof window === 'undefined') return false;
    return !!localStorage.getItem('seekers_auth_token');
  },

  logout(): void {
    if (typeof window === 'undefined') return;
    try {
      apiClient.request('/auth/logout', { method: 'POST' }).catch(() => {});
    } catch {}
    localStorage.removeItem('seekers_auth_token');
    localStorage.removeItem('seekers_auth_user');
    window.dispatchEvent(new Event('seekers_auth_changed'));
    window.location.href = '/login';
  },
};
